### ISSUE TITLE
main branch is not updated？

### ISSUE THREAD

**Issue by WSTao** [hitfee01/rtm3d#1]
What is the difference between the three branch versions？

**Comment by hitfeelee** [comment]
base part of rtm3d is implemented (not include 3d properties) on main branch,  the result of training shows that the effect of vertexs of objects in vertex heat map is not good.
the implementation on smoke branch,  removing vertex heat map, adding 3d properties regression according to smoke,  and thus optimising encode, decode ,losses of 3d properties . But it includes redundant implementation ,such as regressing the diffs of vertexs to center
simple-smoke branch base on smoke branch, but removing redundant implementation, merging detect headers, and removing dialted conv(the op runs very slowly in cpu)

**Comment by hitfeelee** [comment]
> What is the difference between the three branch versions？

base part of rtm3d is implemented (not include 3d properties) on main branch, the result of training shows that the effect of vertexs of objects in vertex heat map is not good.
the implementation on smoke branch, removing vertex heat map, adding 3d properties regression according to smoke, and thus optimising encode, decode ,losses of 3d properties . But it includes redundant implementation ,such as regressing the diffs of vertexs to center
simple-smoke branch base on smoke branch, but removing redundant implementation, merging detect headers, and removing dialted conv(the op runs very slowly in cpu)

**Comment by WSTao** [comment]
Okay. I understand. Thanks very much
