### ISSUE TITLE
Why does the code use the [sin, cos] format instead of the implementation of MultiBin?

### ISSUE THREAD

**Issue by WSTao** [hitfee01/rtm3d#2]
I run yolo3d and simple-smoke and find that the orientation of simple-smoke is more accurate. and the effect of multibin is not as good as that of direct regression?

**Comment by hitfeelee** [comment]
In fact , multibin should be better than direct regression (I have verified it in past project). I guess,  The different networks lead to the result above.

**Comment by WSTao** [comment]
Okey, Thx!
