### ISSUE TITLE
Trained simple-smoke

### ISSUE THREAD

**Issue by WSTao** [hitfee01/rtm3d#3]
Hi!
I trained simple-smoke with rtm3d_resnet18_kitti.yaml file, the train loss began to decrease, and the test result was getting better. However, after 20 epochs, although the loss was decreasing, the test effect was decreasing, and the last test results were completely incorrect. What's the matter?

**Comment by hitfeelee** [comment]
I'm sorry WSTao , I dealed with other things in recent past time. I never  encounter  your matter in many training processes.

**Comment by WSTao** [comment]
> I'm sorry WSTao , I dealed with other things in recent past time. I never encounter your matter in many training processes.

Thanks，The problem is caused by my hyper parameter configuration and has been solved
